### ISSUE TITLE
no_std

### ISSUE THREAD

**Issue by zendurix** [bodil/smartstring#10]
Will this be hard to add `no_std` optional feature?
I can try to make PR with `alloc` etc

**Comment by bodil** [comment]
`no_std` seems very feasible to me, as long as it's not also `no_alloc`, of course. A PR would be very welcome.

**Comment by zendurix** [comment]
https://github.com/bodil/smartstring/pull/11

**Comment by bodil** [comment]
OK, you might want to look over that commit and reopen if I've done something silly, otherwise I'll tag a release with it shortly.
