### ISSUE TITLE
Illegal dereference

### ISSUE THREAD

**Issue by Plecra** [bodil/smartstring#14]
https://github.com/bodil/smartstring/blob/55a7c5003a151d731daedc70a31220b98745809c/src/lib.rs#L292-L293

As I understand Rust's safety rules, this is UB. `String` doesn't have a fixed representation, and nothing's stopping the compiler from choosing to stuff it with some padding bytes that `InlineString` doesn't account for.

It seems like [the InlineString implementation](https://github.com/bodil/smartstring/blob/55a7c5003a151d731daedc70a31220b98745809c/src/inline.rs#L40) acknowledges this, but that assertion is made too late.

This isn't difficult to fix - we could construct the `String` on demand with `from_raw_parts`, or (if that ends up hurting performance) implement the allocation ourselves.

**Comment by ZaneHannanAU** [comment]
Potential - but dumb fix... which requires a lot of effort.

```rust
#[repr(C)]
union SmartStringInternal<Mode: SmartStringMode> {
  ptr_cap_len: (*mut u8, usize, usize),
  data: (Marker, Mode::Array),
  marker: Marker,
}
```

In this way, you can isolate the unsafety far easier - but as it stands, this is a nightly only feature. Clone would need a wrapper type as well, unfortunately.

It isn't much better than what's available, though, it'd drop some transmute into the language itself.
