### ISSUE TITLE
Implement PartialEq<&str> ?

### ISSUE THREAD

**Issue by manuthambi** [bodil/smartstring#15]
`std::string::String ` implements `PartialEq<&str>`. This allows us to compare a slice of Strings with a slice of `&str`.
It would be very useful to have while comparing slices of strings.

Right now I have to do this:
```
let smartstrings:  &[smartstring::alias::String] = &["hello".into(), "world".into()];
//assert_eq!(smartstrings, &["hello", "world"]);  // Doesn't work
assert!(smartstrings.iter().eq(["hello", "world"].iter().copied())); // works
```

**Comment by manuthambi** [comment]
I can send you a pull request, if you like this to be added.

**Comment by bodil** [comment]
That would be great.
