### ISSUE TITLE
Remove dependency on `arbitrary`

### ISSUE THREAD

**Issue by Plecra** [bodil/smartstring#3]
I'm not sure what it's actually being used for at the moment, but it seems like it's just something to do with the tests. Does it need to be in the `dependency` list?

**Comment by bodil** [comment]
You're aware it's an optional dependency?

**Comment by Plecra** [comment]
Thanks for responding 😊 sorry I left this hanging.

Maybe it could be a little clearer that the extra features aren't public API and are just for the tests? If that's the case, at least 😉

**Comment by bodil** [comment]
Yes, I won't say it doesn't annoy me too, it means having to maintain a specific list of features to be documented on docs.rs so the API docs aren't full of tests, but unfortunately it's the least awful way I've found to export the integration tests to libFuzzer. If you can see a better way, do please let me know, but until then I'm afraid we're stuck with the feature flag.
