### ISSUE TITLE
Convert integer to smartstring

### ISSUE THREAD

**Issue by douglas-raillard-arm** [bodil/smartstring#37]
Hi,

I was trying to efficiently convert an integer to a smartstring (actually, I want to append it at the end of a smartstring). `String` has the `ToString` trait so you can just `mystr.push_str(43.to_string())`, but there does not seem to be any equivalent for smartstring, unless you convert `String` to smartstring (but this would allocate then free which would be a perf issue for me).

Any recommendation on how to proceed ?

**Comment by schungx** [comment]
It might be difficult to avoid allocation because the text you want to write into the string may push the string over its inline limit.

**Comment by douglas-raillard-arm** [comment]
Actually I realized I can use `write!()` macro to format the number in the smartstring.

> It might be difficult to avoid allocation 

I meant that I don't want a forced allocation on the typical path (numbers < 64, fixed string prefix of 8 char). Allocating if there is a functional need is ok.

**Comment by schungx** [comment]
> Actually I realized I can use `write!()` macro to format the number in the smartstring.

Great deal.  I didn't know that!
