### ISSUE TITLE
panic in InlineString::len in Rust 1.67

### ISSUE THREAD

**Issue by AdamRzepka** [bodil/smartstring#38]
Hi,

It looks like upgrade to the latest Rust (1.67) broke `smartstring` crate. Any serious usage of it triggers `assert!(len <= MAX_INLINE);` in a function `InlineString::len`. Judging by the comment above the assert, something has changed in String memory layout.

Adam

**Comment by ryanrussell** [comment]
Seeing the same behavior

```bash
 Build graph layer ... thread '<unnamed>' panicked at 'assertion failed: len <= MAX_INLINE', /home/worker/.cargo/registry/src/github.com-1ecc6299db9ec823/smartstring-0.2.9/src/inline.rs:41:9
 ```
 
 ```bash
 rustc --version
rustc 1.67.0 (fc594f156 2023-01-24)
```

**Comment by schungx** [comment]
Strangely I am not seeing the same with 1.67...  are you running on a 32-bit architecture?

**Comment by AdamRzepka** [comment]
No, I'm using x64 on Windows.

**Comment by ryanrussell** [comment]
ubuntu 20, x86_64

Found it tinkering iwth osm addresses. Here's a a minimal way to re-create:

```
# https://github.com/Qwant/addresses-importer/tree/master/importers/osm

# Get a small pbf
wget https://download.geofabrik.de/north-america/us/maryland-latest.osm.pbf

# Clone repo and try to import it
git clone git@github.com:Qwant/addresses-importer.git
cd addresses-importer/importers/osm
cargo run --release --  /full/path/to/maryland-latest.osm.pbf
```

Confirmed changing back to `rustup default 1.66.1` runs, but `1.67.0` will not.

**Comment by schungx** [comment]
How about running under debug? Still the same error?

**Comment by ryanrussell** [comment]
Yes, still happens under debug mode.

Appears related to multilingual names in this particular example.


When I dig a bit deeper:

```bash
0 pending, 0 deps, objs: 167890
0 pending, 0 deps, objs: 167891
thread '<unnamed>' panicked at 'assertion failed: len <= MAX_INLINE', /home/worker/.cargo/registry/src/github.com-1ecc6299db9ec823/smartstring-0.2.9/src/inline.rs:41:9
0 pending, 0 deps, objs: 167892
0 pending, 0 deps, objs: 167893
```

```bash
KV: ("name", "Baltimore")
KV: ("name:ar", "بالتيمور")
KV: ("name:az", "Baltimor")
KV: ("name:be", "Балтымар")
KV: ("name:de", "Baltimore")
KV: ("name:en", "Baltimore")
KV: ("name:fa", "بالتیمور")
KV: ("name:fr", "Baltimore")
KV: ("name:he", "בולטימור")
KV: ("name:hi", "\0\0\0\0\0\0\0thread 'main' panicked at 'byte index 7 is not a char boundary; it is inside '\0' (bytes 6..7) of `�`@�`', library/core/src/fmt/mod.rs:2426:30

```

Hope this helps.

This should be reproducible given the snippet above

**Comment by schungx** [comment]
Looks like nulls inside a string...

Does it choke on zero bytes?

**Comment by TeXitoi** [comment]
Maybe that's an issue with 0.2 as it depends on the string internal representation, and that's fixed by 1.0.0 that doesn't anymore?

**Comment by ryanrussell** [comment]
@TeXitoi That sounds like it's likely the case. I tried real quick to upgrade that open source repo to 1.0, but it threw some other errors. 

I don't want to close this issue as I didn't create it, but it seems logical to disregard my example as related to a deprecated version.

@AdamRzepka -- Are you seeing this error on a 1.x? If so, can you give a reproducible example?

**Comment by AdamRzepka** [comment]
Yes, I can confirm that upgrade to 1.0.1 fixed the problem. Sorry for not checking this earlier. I'm closing the issue.
