### ISSUE TITLE
More traits? (Eq, Hash, Ord..)

### ISSUE THREAD

**Issue by myfreeweb** [bodil/smartstring#9]
[kstring](https://github.com/cobalt-org/kstring) implements `Eq`, `Hash`, `Ord` which makes it usable for map keys. But smartstring currently doesn't, so it's not usable as a replacement for kstring..

**Comment by bodil** [comment]
But it does? https://github.com/bodil/smartstring/blob/master/src/lib.rs#L1061-L1085 Are these not working for you?

**Comment by myfreeweb** [comment]
Oh. `LazyCompact` is just the mode, I thought it's an alias for the string with the mode already, I was trying to use `LazyCompact` instead of `SmartString<LazyCompact>`. \*facepalm\* sorry
